# Generated by Django 5.2.1 on 2025-07-10 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True, verbose_name='ID du lot')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('total_predictions', models.IntegerField(default=0, verbose_name='Nombre de prédictions')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Lot de prédictions',
                'verbose_name_plural': 'Lots de prédictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XGBoostPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de prédiction')),
                ('prediction_value', models.FloatField(verbose_name='Valeur prédite (kWh)')),
                ('confidence', models.FloatField(default=0.95, verbose_name='Niveau de confiance')),
                ('model_version', models.CharField(default='XGBoost_v1.0', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Prédiction XGBoost',
                'verbose_name_plural': 'Prédictions XGBoost',
                'ordering': ['date'],
                'unique_together': {('date', 'model_version')},
            },
        ),
    ]
