# Generated by Django 5.2.1 on 2025-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('result_label', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_session', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Image Uploadée',
                'verbose_name_plural': 'Images Uploadées',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
